spring:
  application:
    name: mauwealthy_service
  profiles:
    active:
      - dev

app:
  cors:
    allowed-origin-patterns:
      - http://localhost:4200
      - http://127.0.0.1:4200
      - http://127.0.0.1:12653
      - https://mauwealthy.my.id
      - https://*.mauwealthy.my.id
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Requested-With
    exposed-headers:
      - Authorization
      - Content-Type
      - Location
    allow-credentials: true
    max-age: 3600

server:
  port: 12653

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/mauwealthy_db
    username: postgres
    password: 13qeadzc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
    username: postgres.czpxqefbzfbfdxfjkufn
    password: 13qeadzcAs!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html